var annotated_dup =
[
    [ "max_0x88_diff_t", "structmax__0x88__diff__t.html", null ],
    [ "max_0x88_t", "structmax__0x88__t.html", null ],
    [ "max_6bit_t", "structmax__6bit__t.html", null ],
    [ "max_board_t", "structmax__board__t.html", "structmax__board__t" ],
    [ "max_captures_t", "structmax__captures__t.html", "structmax__captures__t" ],
    [ "max_check_t", "structmax__check__t.html", "structmax__check__t" ],
    [ "max_engine_init_params_t", "structmax__engine__init__params__t.html", "structmax__engine__init__params__t" ],
    [ "max_engine_material_cfg_t", "unionmax__engine__material__cfg__t.html", null ],
    [ "max_engine_psqt_param_t", "structmax__engine__psqt__param__t.html", null ],
    [ "max_engine_strat_param_t", "structmax__engine__strat__param__t.html", "structmax__engine__strat__param__t" ],
    [ "max_engine_t", "structmax__engine__t.html", "structmax__engine__t" ],
    [ "max_eval_params_t", "structmax__eval__params__t.html", "structmax__eval__params__t" ],
    [ "max_fen_parse_result_t", "structmax__fen__parse__result__t.html", "structmax__fen__parse__result__t" ],
    [ "max_loclist_t", "structmax__loclist__t.html", "structmax__loclist__t" ],
    [ "max_movelist_t", "structmax__movelist__t.html", "structmax__movelist__t" ],
    [ "max_nodescore_t", "structmax__nodescore__t.html", "structmax__nodescore__t" ],
    [ "max_piececode_t", "structmax__piececode__t.html", null ],
    [ "max_piecemask_t", "structmax__piecemask__t.html", null ],
    [ "max_pieces_t", "structmax__pieces__t.html", "structmax__pieces__t" ],
    [ "max_scorelist_t", "structmax__scorelist__t.html", "structmax__scorelist__t" ],
    [ "max_search_result_t", "structmax__search__result__t.html", null ],
    [ "max_smove_t", "structmax__smove__t.html", "structmax__smove__t" ],
    [ "max_state_stack_t", "structmax__state__stack__t.html", "structmax__state__stack__t" ],
    [ "max_state_t", "structmax__state__t.html", "structmax__state__t" ],
    [ "max_ttbl_t", "structmax__ttbl__t.html", "structmax__ttbl__t" ],
    [ "max_ttentry_t", "structmax__ttentry__t.html", "structmax__ttentry__t" ],
    [ "max_zobrist_elements_t", "structmax__zobrist__elements__t.html", "structmax__zobrist__elements__t" ],
    [ "max_zobrist_xoshiro256", "structmax__zobrist__xoshiro256.html", null ]
];