
#include "max/square.h"

const max_increment_t  MAX_DIAGONALS[4] = {
    MAX_INCREMENT_UR,
    MAX_INCREMENT_UL,
    MAX_INCREMENT_DR,
    MAX_INCREMENT_DL,
};

const max_increment_t MAX_CARDINALS[4] = {
    MAX_INCREMENT_UP,
    MAX_INCREMENT_LEFT,
    MAX_INCREMENT_RIGHT,
    MAX_INCREMENT_DOWN
};

const max_increment_t MAX_PAWNSIDES[2] = {
    MAX_INCREMENT_RIGHT,
    MAX_INCREMENT_LEFT
};

const max_increment_t MAX_PAWN_DIR[2] = {
    MAX_INCREMENT_UP,
    MAX_INCREMENT_DOWN
};

const max_increment_t MAX_KNIGHT_MOVES[8] = {
    MAX_INCREMENT_UP    + MAX_INCREMENT_UR,
    MAX_INCREMENT_UP    + MAX_INCREMENT_UL,
    MAX_INCREMENT_DOWN  + MAX_INCREMENT_DR,
    MAX_INCREMENT_DOWN  + MAX_INCREMENT_DL,
    MAX_INCREMENT_RIGHT + MAX_INCREMENT_UR,
    MAX_INCREMENT_RIGHT + MAX_INCREMENT_DR,
    MAX_INCREMENT_LEFT  + MAX_INCREMENT_UL,
    MAX_INCREMENT_LEFT  + MAX_INCREMENT_DL,
};


