name: Build and Deploy Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Doxygen HTML Files
    steps:
      - uses: ssciwr/doxygen-install@v1
      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.20.x'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DMAX_DOC=ON
      - name: Build Doxygen HTML
        run: >
          cmake --build ${{ github.workspace }}/build -t max-doc
      - name: Deploy to Github Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/build/doc/html
          single-commit: true
